#Mon Mar 04 15:45:11 UTC 2024
micronaut:
  application:
    name: micronaut-microservices
  server:
    port: ${SERVER_PORT:8090}

hello:
  world:
    message: "Hello from application.yml"
    translation:
      de: "Hallo Welt"
      en: "Hello World"